(()=>{
const P={car:'<path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"/><circle cx="7" cy="17" r="2"/><path d="M9 17h6"/><circle cx="17" cy="17" r="2"/>',
utensils:'<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"/>',
dots:'<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>',
shirt:'<path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"/>',
basket:'<path d="m15 11-1 9"/><path d="m19 11-4-7"/><path d="M2 11h20"/><path d="m3.5 11 1.6 7.4a2 2 0 0 0 2 1.6h9.8a2 2 0 0 0 2-1.6l1.7-7.4"/><path d="M4.5 15.5h15"/><path d="m5 11 4-7"/><path d="m9 11 1 9"/>',
house:'<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',
sprout:'<path d="M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3"/><path d="M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4"/><path d="M5 21h14"/>',
ok:'<path d="M20 6 9 17l-5-5"/>',chev:'<path d="m9 18 6-6-6-6"/>',chevl:'<path d="m15 18-6-6 6-6"/>',pen:'<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/>',x:'<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',zoek:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',repeat:'<path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/>',gift:'<rect x="3" y="8" width="18" height="4" rx="1"/><path d="M12 8v13"/><path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7"/><path d="M7.5 8a2.5 2.5 0 0 1 0-5C10 3 12 8 12 8s2-5 4.5-5a2.5 2.5 0 0 1 0 5"/>',pill:'<path d="m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z"/><path d="m8.5 8.5 7 7"/>',coffee:'<path d="M10 2v2"/><path d="M14 2v2"/><path d="M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1"/><path d="M6 2v2"/>',book:'<path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/>'};
const ico=(n,s=16,w=2)=>`<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex:0 0 auto;display:block">${P[n]}</svg>`;
const CAT={vervoer:['Vervoer','teal','car'],uit:['Uit eten','orange','utensils'],overig:['Overig','gray','dots'],kleding:['Kleding','red','shirt'],boodschappen:['Boodschappen','green','basket'],wonen:['Wonen','blue','house'],tuin:['Tuin','olijf','sprout'],abonnementen:['Abonnementen','purple','repeat'],cadeaus:['Cadeaus','purple','gift'],drogisterij:['Drogisterij','gray','pill'],koffie:['Koffie & lunch','orange','coffee'],hobby:['Hobby','olijf','book'],energie:['Energie','blue','house'],verzekering:['Verzekeringen','teal','car'],huisdier:['Huisdier','olijf','sprout'],zorg:['Zorg','red','pill'],sport:['Sport','teal','dots']};
const ITEMS=[
{id:1,m:'Shell Zwolle',v:61.20,d:'3 okt',r:'Betaalpas',g:'vervoer',why:'Vorige 6× ook Vervoer',alt:[['boodschappen','AH to go bij Shell, 1×'],['overig',''],['uit','']]},
{id:2,m:'Tikkie · Sanne',v:18.50,d:'2 okt',r:'Tikkie',g:'uit',why:'Tikkies van Sanne: 3× Uit eten',alt:[['boodschappen','Sanne, 1×'],['cadeaus','Sanne, 1×'],['overig','']]},
{id:3,m:'Bol.com',v:34.99,d:'1 okt',r:'iDEAL',g:'overig',why:'Wisselend, laatste keer Overig',alt:[['kleding','Bol.com, 2×'],['hobby','Bol.com, 2×'],['cadeaus','Bol.com, 1×']]},
{id:4,m:'Zeeman',v:12.47,d:'30 sep',r:'Betaalpas',g:'kleding',why:'Vorige 2× ook Kleding',alt:[['drogisterij','Zeeman, 1×'],['wonen',''],['overig','']]}];
const N='font-variant-numeric:tabular-nums;white-space:nowrap';
const eur=v=>'−€ '+v.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2});
const cv=k=>`var(--cat-${CAT[k][1]})`,cb=k=>`var(--cat-${CAT[k][1]}-bg)`;
const chip=(k,s)=>`<span style="flex:0 0 auto;width:${s}px;height:${s}px;border-radius:999px;display:grid;place-items:center;background:${cb(k)};color:${cv(k)}">${ico(CAT[k][2],s*.46,2)}</span>`;
const gok=(k,btn)=>`<${btn?'button data-kies="'+k+'"':'span'} style="display:inline-flex;align-items:center;gap:6px;${btn?'height:40px;padding:0 14px 0 8px;border:0;cursor:pointer;font-family:inherit;font-size:14px':'height:24px;padding:0 9px 0 5px;font-size:12px'};border-radius:999px;background:${cb(k)};color:${cv(k)};font-weight:600">${ico(CAT[k][2],btn?16:12,2.2)}<span style="color:${btn?'var(--text)':cv(k)}">${CAT[k][0]}</span></${btn?'button':'span'}>`;
const btn=(act,txt,icon,primary)=>`<button data-act="${act}" style="flex:1;height:48px;border:0;border-radius:999px;display:flex;align-items:center;justify-content:center;gap:6px;font-family:inherit;font-size:15px;font-weight:600;cursor:pointer;background:${primary?'var(--accent)':'var(--surface-sunken)'};color:${primary?'var(--accent-fg)':'var(--text)'}">${ico(icon,16,2.4)}${txt}</button>`;
const shell=x=>`<div style="display:flex;flex-direction:column;padding:20px;border-radius:var(--radius-lg);background:var(--surface-raised);border:1px solid var(--border);box-shadow:var(--shadow-card);color:var(--text);font-family:var(--font-sans);overflow:hidden">${x}</div>`;

function mount(el){
const mob=el.dataset.modus==='telefoon',scr=el.closest('[data-screen-label]');const touch=!(scr&&/desktop/.test(scr.dataset.screenLabel||''));
let open=ITEMS.map(i=>i.id),log=[],andere=false,busy=false;
const it=id=>ITEMS.find(i=>i.id===id);
const teller=()=>scr&&scr.querySelectorAll('[data-nk-teller]').forEach(t=>{t.textContent=open.length;t.style.display=open.length?'':'none'});
const meld=(id,k)=>scr&&scr.dispatchEvent(new CustomEvent('nk',{detail:{id,k,n:CAT[k][0],chip:chip(k,36)}}));
const kRij=(k,hint)=>`<button data-kies="${k}" data-zoek="${CAT[k][0].toLowerCase()}" style="display:flex;align-items:center;gap:12px;width:100%;min-height:44px;padding:0 10px;margin:0 -10px;box-sizing:content-box;border:0;border-radius:10px;background:transparent;color:var(--text);font-family:inherit;font-size:15px;text-align:left;cursor:pointer" onmouseenter="this.style.background='var(--surface-sunken)'" onmouseleave="this.style.background='transparent'">${chip(k,28)}<span style="flex:1">${CAT[k][0]}</span>${hint?`<span style="font-size:12px;color:var(--text-subtle)">${hint}</span>`:''}</button>`;
const gTile=k=>`<button data-kies="${k}" data-zoek="${CAT[k][0].toLowerCase()}" style="display:flex;align-items:center;gap:10px;min-width:0;min-height:52px;padding:0 12px 0 10px;border:1px solid var(--border);border-radius:12px;background:var(--surface-raised);color:var(--text);font-family:inherit;font-size:14px;font-weight:500;text-align:left;cursor:pointer;box-sizing:border-box">${chip(k,28)}<span style="min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${CAT[k][0]}</span></button>`;
const bTile=(k,hint)=>`<button data-kies="${k}" style="display:flex;align-items:center;gap:12px;width:100%;min-height:56px;padding:0 14px 0 10px;border:0;border-radius:14px;background:${cb(k)};color:var(--text);font-family:inherit;text-align:left;cursor:pointer;box-sizing:border-box"><span style="flex:0 0 auto;width:36px;height:36px;border-radius:999px;display:grid;place-items:center;background:var(--surface-raised);color:${cv(k)}">${ico(CAT[k][2],18,2.2)}</span><span style="flex:1;min-width:0;font-size:15px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${CAT[k][0]}</span>${hint?`<span style="flex:0 1 auto;min-width:0;font-size:12px;color:var(--text-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${hint}</span>`:''}</button>`;
const lbl=t=>`<span style="font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--text-subtle);padding:12px 0 2px">${t}</span>`;
function kiezer(c){const sug=c.alt.map(a=>a[0]),rest=Object.keys(CAT).filter(k=>k!==c.g&&!sug.includes(k)).sort((a,b)=>CAT[a][0].localeCompare(CAT[b][0],'nl'));
return `<div data-kiezer style="display:flex;flex-direction:column;margin-top:14px"><div style="display:flex;align-items:center;gap:8px"><label style="flex:1;display:flex;align-items:center;gap:8px;height:44px;padding:0 14px;border-radius:999px;background:var(--surface-sunken);color:var(--text-muted)">${ico('zoek',16,2.2)}<input data-zoekveld placeholder="Zoek categorie" style="flex:1;min-width:0;border:0;outline:0;background:transparent;font-family:inherit;font-size:15px;color:var(--text)"></label><button data-act="terug" style="height:44px;padding:0 6px;border:0;background:transparent;color:var(--text-muted);font-family:inherit;font-size:14px;font-weight:500;cursor:pointer">Annuleer</button></div><div data-sug style="display:flex;flex-direction:column;padding-bottom:6px">${lbl('Waarschijnlijk')}<div style="display:flex;flex-direction:column;gap:8px">${c.alt.map(([k,h])=>bTile(k,h)).join('')}</div></div><div style="display:flex;flex-direction:column"><button data-act="alle" data-allebtn style="display:flex;align-items:center;justify-content:space-between;width:100%;min-height:44px;margin-top:6px;padding:0 4px;border:0;background:transparent;color:var(--accent);font-family:inherit;font-size:14px;font-weight:600;cursor:pointer">Alle categorieën<span style="display:flex">${ico('chev',16,2.4)}</span></button><div data-alle data-grid style="display:none;flex-direction:column;gap:6px;margin-top:6px;max-height:236px;overflow-y:auto;padding:2px">${rest.map(k=>gTile(k)).join('')}${sug.map(k=>gTile(k).replace('display:flex;','display:none;').replace('data-kies','data-dub data-kies')).join('')}</div><span data-leeg style="display:none;padding:12px 0;font-size:14px;color:var(--text-muted)">Geen categorie gevonden</span></div></div>`}
function zoek(){const f=el.querySelector('[data-zoekveld]');if(!f)return;if(!mob)f.focus({preventScroll:true});f.addEventListener('input',()=>{const q=f.value.trim().toLowerCase(),s=el.querySelector('[data-sug]');s.style.display=q?'none':'flex';const al=el.querySelector('[data-alle]'),ab=el.querySelector('[data-allebtn]');if(q){al.style.display='flex';ab.style.display='none'}else if(!al.dataset.open){al.style.display='none';ab.style.display='flex'}let n=0;el.querySelectorAll('[data-alle] [data-kies]').forEach(b=>{const dub=b.hasAttribute('data-dub'),hit=q?b.dataset.zoek.includes(q):!dub;b.style.display=hit?'flex':'none';if(hit)n++});el.querySelector('[data-leeg]').style.display=n?'none':'block'})}
function huidig(c){return `<div data-swipe style="position:relative;touch-action:pan-y;transition:transform .2s,opacity .2s"><div style="display:flex;align-items:center;gap:14px">${chip(c.g,44)}<span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px"><span style="font-size:17px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${c.m}</span><span style="font-size:13px;color:var(--text-muted)">${c.d} · ${c.r}</span></span><b style="font-size:20px;font-weight:600;${N}">${eur(c.v)}</b></div>`+
(andere?kiezer(c)
:`<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:16px;padding:10px 12px;border-radius:var(--radius-sm);background:var(--surface-sunken);font-size:14px"><span style="color:var(--text-muted)">Onze gok</span>${gok(c.g)}<span style="flex:1"></span><span style="font-size:12px;color:var(--text-muted)">${c.why}</span></div><div style="display:flex;gap:8px;margin-top:12px">${btn('klopt','Klopt','ok',1)}${btn('andere','Andere','pen',0)}</div>`)+`</div>`}
function kop(){const tot=ITEMS.length,k=tot-open.length;return `<div style="display:flex;align-items:center;gap:10px;padding-bottom:16px"><b style="flex:1;font-size:15px;font-weight:600">Nakijken</b><span style="display:flex;gap:4px">${ITEMS.map((_,i)=>`<span style="width:${i===k?16:6}px;height:6px;border-radius:999px;background:${i<k?'var(--accent-soft)':i===k?'var(--accent)':'var(--border)'};transition:width .2s"></span>`).join('')}</span><span style="font-size:13px;color:var(--text-muted);${N}">${k+1} van ${tot}</span></div>`}
function hierna(){const rest=open.slice(1,4);if(!rest.length)return `<div style="display:flex;flex-direction:column;justify-content:center;height:100%;font-size:14px;color:var(--text-muted)">Dit is de laatste.</div>`;return `<span style="font-size:12px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--text-subtle);padding-bottom:4px">Hierna</span>`+rest.map((id,i)=>{const c=it(id);return `<div style="display:flex;align-items:center;gap:12px;min-height:60px;${i?'border-top:1px solid var(--border)':''}"><span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:4px"><span style="display:flex;align-items:baseline;gap:8px"><span style="flex:1;min-width:0;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${c.m}</span><span style="font-size:14px;${N}">${eur(c.v)}</span></span><span style="display:flex;align-items:center;gap:8px;font-size:12px;color:var(--text-muted)">${gok(c.g)}${c.d}</span></span><button data-snel="${id}" title="Klopt" aria-label="${c.m}: klopt" style="flex:0 0 auto;width:36px;height:36px;border:0;border-radius:999px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent-hover);cursor:pointer">${ico('ok',16,2.6)}</button></div>`}).join('')+(open.length>2?`<button data-act="alles" style="align-self:flex-start;margin-top:8px;height:36px;padding:0;border:0;background:transparent;color:var(--accent);font-family:inherit;font-size:14px;font-weight:600;cursor:pointer;display:flex;align-items:center;gap:6px">${ico('ok',15,2.6)}Alle ${open.length} kloppen</button>`:'')}
function klaar(){const aan=log.filter(l=>l.k!==it(l.id).g).length;return shell(`<div style="display:flex;align-items:center;gap:14px"><span style="flex:0 0 auto;width:44px;height:44px;border-radius:999px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent-hover)">${ico('ok',20,2.6)}</span><span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px"><b style="font-size:15px;font-weight:600">Alles nagekeken</b><span style="font-size:13px;color:var(--text-muted)">${log.length} bevestigd${aan?`, waarvan ${aan} aangepast`:''}. Deze card verdwijnt morgen.</span></span><button data-act="reset" style="height:40px;padding:0 12px;border:0;border-radius:999px;background:transparent;color:var(--accent);font-family:inherit;font-size:14px;font-weight:600;cursor:pointer">Ongedaan</button></div>`)}
const pil=(act,txt,icon,primary)=>`<button data-act="${act}" style="flex:0 0 auto;height:44px;padding:0 ${primary?18:14}px;border:0;border-radius:999px;display:flex;align-items:center;gap:6px;font-family:inherit;font-size:14px;font-weight:600;cursor:pointer;background:${primary?'var(--accent)':'var(--surface-sunken)'};color:${primary?'var(--accent-fg)':'var(--text)'}">${ico(icon,15,2.4)}${txt}</button>`;
function stapel(c){const n=Math.min(open.length-1,2),lag=(i)=>`<div style="position:absolute;left:${(i+1)*12}px;right:${(i+1)*12}px;bottom:${(n-1-i)*6}px;height:40px;border-radius:var(--radius-lg);background:var(--surface-raised);border:1px solid var(--border);opacity:${i?.55:.8}"></div>`;
return `<div style="position:relative;padding-bottom:${n*6}px;font-family:var(--font-sans);color:var(--text)">${[...Array(n)].map((_,i)=>lag(n-1-i)).join('')}<div style="position:relative;border-radius:var(--radius-lg);overflow:hidden;box-shadow:var(--shadow-card)"><div data-laag="r" style="position:absolute;inset:0;background:var(--accent);color:var(--accent-fg);display:flex;align-items:center;gap:6px;padding-left:20px;font-size:15px;font-weight:600;opacity:0">${ico('ok',18,2.6)}Klopt</div><div data-laag="l" style="position:absolute;inset:0;background:var(--surface-sunken);color:var(--text);display:flex;align-items:center;justify-content:flex-end;gap:6px;padding-right:20px;font-size:15px;font-weight:600;opacity:0">Andere${ico('pen',16,2.2)}</div><div data-vlak data-swipe style="position:relative;touch-action:pan-y;padding:16px;border-radius:var(--radius-lg);background:var(--surface-raised);border:1px solid var(--border);box-sizing:border-box"><div style="display:flex;align-items:center;gap:12px">${chip(c.g,40)}<span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:4px"><span style="display:flex;align-items:baseline;gap:8px"><span style="flex:1;min-width:0;font-size:15px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${c.m}</span><span style="font-size:15px;font-weight:600;${N}">${eur(c.v)}</span></span><span style="display:flex;align-items:center;gap:8px;font-size:12px;color:var(--text-muted)">${gok(c.g)}${c.d}</span></span></div>`+
(andere?kiezer(c)
:`<span style="display:block;margin:8px 0 0 52px;font-size:12px;color:var(--text-subtle)">${c.why}</span><div style="display:flex;align-items:center;gap:8px;margin-top:12px"><span style="flex:1;font-size:13px;color:var(--text-muted)">${open.length>1?`Nog ${open.length-1} na deze`:'Laatste'}</span>${touch?`<span style="display:flex;align-items:center;gap:10px;font-size:13px;font-weight:600;color:var(--text-muted)"><span style="display:flex;align-items:center;gap:3px">${ico('chevl',13,2.4)}andere</span><span style="display:flex;align-items:center;gap:3px;color:var(--accent)">klopt${ico('chev',13,2.4)}</span></span>`:pil('andere','Andere','pen',0)+pil('klopt','Klopt','ok',1)}</div>`)+`</div></div></div>`}
function render(enter){teller();if(!open.length){const h=el.offsetHeight;el.style.overflow='hidden';el.style.height=h+'px';requestAnimationFrame(()=>{el.style.transition='height .25s ease,opacity .2s ease';el.style.height='0px';el.style.opacity='0'});setTimeout(()=>{el.innerHTML='';el.style.display='none'},260);return}const c=it(open[0]);
if(mob){el.innerHTML=stapel(c);const v=el.querySelector('[data-vlak]');if(enter&&v){v.style.transition='none';v.style.transform='translateY(8px)';v.style.opacity='0';requestAnimationFrame(()=>requestAnimationFrame(()=>{v.style.transition='transform .2s,opacity .2s';v.style.transform='';v.style.opacity='1'}))}swipe();zoek();return}
const left=kop()+huidig(c);
el.innerHTML=shell(`<div style="display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:28px"><div style="display:flex;flex-direction:column">${left}</div><div style="display:flex;flex-direction:column;padding-left:28px;border-left:1px solid var(--border)">${hierna()}</div></div>`);
const sw=el.querySelector('[data-swipe]');if(enter&&sw){sw.style.transition='none';sw.style.transform='translateX(-14px)';sw.style.opacity='0';requestAnimationFrame(()=>requestAnimationFrame(()=>{sw.style.transition='transform .2s,opacity .2s';sw.style.transform='';sw.style.opacity='1'}))}zoek()}
function bevestig(id,k){if(busy)return;const c=it(id);const sw=el.querySelector('[data-swipe]');const first=id===open[0];const go=()=>{log.push({id,k:k||c.g});open=open.filter(x=>x!==id);andere=false;busy=false;meld(id,k||c.g);render(first)};if(first&&sw){busy=true;const v=mob?el.querySelector('[data-vlak]'):sw;v.style.transition='transform .2s,opacity .2s';v.style.transform=mob?'translateX(110%)':'translateX(40px)';v.style.opacity='0';setTimeout(go,190)}else go()}
function swipe(){if(!touch)return;const v=el.querySelector('[data-vlak]'),R=el.querySelector('[data-laag="r"]'),L=el.querySelector('[data-laag="l"]');if(!v||andere)return;let x0=null,dx=0;
v.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,label'))return;x0=e.clientX;dx=0;v.style.transition='none';v.setPointerCapture(e.pointerId)});
v.addEventListener('pointermove',e=>{if(x0==null)return;dx=Math.max(-140,Math.min(140,e.clientX-x0));v.style.transform=`translateX(${dx}px)`;R.style.opacity=dx>0?Math.min(dx/90,1):0;L.style.opacity=dx<0?Math.min(-dx/90,1):0});
const up=()=>{if(x0==null)return;x0=null;v.style.transition='transform .2s';if(dx>90){bevestig(open[0])}else if(dx<-90){v.style.transform='';R.style.opacity=L.style.opacity=0;andere=true;render()}else{v.style.transform='';R.style.opacity=L.style.opacity=0}};
v.addEventListener('pointerup',up);v.addEventListener('pointercancel',up)}
el.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!el.contains(b))return;e.stopPropagation();const a=b.dataset.act;
if(b.dataset.kies)bevestig(open[0],b.dataset.kies);else if(b.dataset.snel)bevestig(+b.dataset.snel);
else if(a==='klopt')bevestig(open[0]);else if(a==='andere'){andere=true;render()}else if(a==='alle'){const al=el.querySelector('[data-alle]');al.dataset.open='1';al.style.display='flex';b.style.display='none'}else if(a==='terug'){andere=false;render()}
else if(a==='alles'){open.forEach(id=>{log.push({id,k:it(id).g});meld(id,it(id).g)});open=[];render()}else if(a==='reset'){open=ITEMS.map(i=>i.id);log=[];andere=false;scr&&scr.dispatchEvent(new CustomEvent('nk',{detail:{reset:true}}));render(true)}});
scr&&scr.addEventListener('nk-ok',e=>{if(open.includes(e.detail.id))bevestig(e.detail.id)});
render();}
const go=()=>document.querySelectorAll('.nakijk').forEach(mount);
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',go):go();
})();
