/* Transacties v2: vier voorstellen voor het detail van een transactie, en de
   rekeningenkaart van Profiel met volgorde (slepen) en verbergen (oog). */
(() => {
const X = window.TX2, { ico, CAT, tone, TX, store, eur, signed, dm, longDate, budgetOf, history, MON, at } = X;
const U = () => X.ui;
const lab = s => `<span style="font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--text-subtle)">${s}</span>`;
const shortDay = d => { const x = at(d); return ['zo','ma','di','wo','do','vr','za'][x.getUTCDay()] + ' ' + dm(d); };
const dmy = d => d.slice(8, 10) + '-' + d.slice(5, 7) + '-' + d.slice(0, 4);

function facts(t) {
  const c = t.cat ? CAT[t.cat] : null, acc = store.acc(t.acc), b = !t.transfer && t.cat && budgetOf(t.cat);
  const refund = TX.find(x => x.refundFor === t.id), refundOf = t.refundFor && TX.find(x => x.id === t.refundFor);
  return { c, acc, b, refund, refundOf };
}
const catBtn = (t, c, big) => `<button data-act="cat" data-id="${t.id}" style="display:inline-flex;align-items:center;gap:8px;min-height:${big ? 44 : 36}px;padding:0 12px 0 ${big ? 6 : 4}px;border-radius:999px;border:0;background:${c ? tone(c).bg : 'var(--surface-sunken)'};color:${c ? tone(c).fg : 'var(--text)'};font:inherit;font-size:${big ? 14 : 13}px;font-weight:600;cursor:pointer;max-width:100%">${c ? `<span style="width:${big ? 32 : 28}px;height:${big ? 32 : 28}px;border-radius:999px;display:grid;place-items:center;background:var(--surface-raised)">${ico(c.icon, 15, 2.2)}</span>` : ''}<span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${t.transfer ? 'Overboeking' : c ? c.name : 'Kies categorie'}</span>${ico('pencil', 13, 2.4)}</button>`;
const bar = (b, h = 6) => { const x = b.spent / b.amount, col = x > 1 ? 'var(--danger)' : x === 1 ? 'var(--border)' : b.kind === 'fixed' ? tone(b.cat).fg : 'var(--accent)'; return `<span style="display:block;position:relative;height:${h}px;border-radius:999px;background:var(--surface-sunken)"><span style="position:absolute;inset:0 auto 0 0;width:${Math.min(100, Math.max(2, x * 100))}%;border-radius:999px;background:${col}"></span></span>`; };
const budgetLine = b => b.kind === 'fixed' ? (b.spent >= b.amount ? 'Betaald' : `Nog ${eur(b.amount - b.spent)} van ${eur(b.amount)}`) : b.left < 0 ? `<span style="color:var(--danger);font-weight:600">${eur(-b.left)} over budget</span>` : b.left === 0 ? 'Helemaal besteed' : `<b style="font-weight:600;color:var(--text)">${eur(b.left)}</b> over van ${eur(b.amount)}`;
const quiet = (icon, label, act = '', id = '') => `<button ${act ? `data-act="${act}" data-id="${id}"` : ''} style="display:inline-flex;align-items:center;gap:8px;min-height:44px;padding:0 16px 0 14px;border-radius:999px;border:1px solid var(--border);background:var(--surface-raised);font:inherit;font-size:14px;font-weight:600;color:var(--text);cursor:pointer;white-space:nowrap">${ico(icon, 16, 2.2)}${label}</button>`;
const refundRow = (f, compact) => f.refund ? `<div style="display:flex;align-items:center;gap:10px;min-height:44px">${U().chip(CAT.splin, compact ? 28 : 32)}<span style="flex:1;min-width:0;display:flex;flex-direction:column"><span style="font-size:14px">${f.refund.who}</span><span style="font-size:12px;color:var(--text-muted)">${shortDay(f.refund.d)} · verrekend met deze uitgave</span></span><span style="font-size:14px;font-weight:600;color:var(--success);font-variant-numeric:tabular-nums">${signed(f.refund.amt)}</span></div>` : f.refundOf ? `<div style="font-size:13px;color:var(--text-muted)">Terug voor <b style="color:var(--text);font-weight:600">${f.refundOf.who}</b> van ${shortDay(f.refundOf.d)}, ${signed(f.refundOf.amt)}</div>` : '';

/* A · Uitklap: blijft in de lijst, feiten als tegels, de banktekst meteen leesbaar. */
function A(t, o) {
  const f = facts(t), tile = (k, v) => `<div style="min-width:0;display:flex;flex-direction:column;gap:4px;padding:10px 12px;border-radius:14px;background:var(--surface-sunken)">${lab(k)}<span style="min-width:0;font-size:14px;display:flex;align-items:center;gap:6px">${v}</span></div>`;
  return `<div style="display:flex;flex-direction:column;gap:10px;padding-left:${o.phone ? 0 : 48}px"><div style="display:grid;grid-template-columns:repeat(${o.phone ? 2 : 4},minmax(0,1fr));gap:8px">${tile('Wanneer', `${shortDay(t.d)} · ${t.tm}`)}${tile('Rekening', `${U().logo(f.acc.bank, 18)}<span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${f.acc.name}</span>`)}<div style="min-width:0;display:flex;flex-direction:column;gap:4px;padding:6px 6px 6px 12px;border-radius:14px;background:var(--surface-sunken)">${lab('Categorie')}${catBtn(t, f.c)}</div>${f.b ? tile(f.b.kind === 'fixed' ? 'Vaste last' : 'Potje', `<span style="font-size:13px;color:var(--text-muted)">${budgetLine(f.b)}</span>`) : tile('Budget', '<span style="color:var(--text-muted)">Telt nergens mee</span>')}</div>${refundRow(f, true)}<div style="display:flex;flex-direction:column;gap:4px;padding:0 2px">${lab('Zoals de bank het schrijft')}<span class="tx-mono" style="font-size:12px;line-height:1.5;color:var(--text-muted);word-break:break-word">${t.desc}</span></div><div style="display:flex;flex-wrap:wrap;gap:8px">${t.amt < 0 && !f.refund ? quiet('link', 'Terugbetaling koppelen') : ''}${quiet('repeat', `Altijd zo voor ${t.who}`, 'cat', t.id)}</div></div>`;
}

/* B · Paneel: alles op een plek, de lijst blijft ernaast staan (telefoon: sheet). */
function B(t, o) {
  const f = facts(t), h = history(t.who), past = h.all.filter(x => x.id !== t.id).slice(0, 3), pad = o.phone ? 20 : 24;
  const sec = (title, body, right = '') => `<section style="display:flex;flex-direction:column;gap:8px"><div style="display:flex;justify-content:space-between;align-items:baseline;padding:0 4px">${lab(title)}${right}</div><div style="display:flex;flex-direction:column;gap:6px;padding:12px 14px;border-radius:18px;background:var(--surface-sunken)">${body}</div></section>`;
  return `<div style="display:flex;flex-direction:column;gap:20px;padding:${o.phone ? 12 : pad}px ${pad}px ${pad + 8}px"><div style="display:flex;flex-direction:column;gap:12px;padding-right:44px"><button data-act="cat" data-id="${t.id}" class="tx-ico" aria-label="Categorie wijzigen" style="position:relative;align-self:flex-start;padding:0;border:0;background:none;cursor:pointer;border-radius:999px">${U().chip(f.c, 52)}<span class="tx-pen" style="opacity:1;width:22px;height:22px">${ico('pencil', 12, 2.4)}</span></button><div style="display:flex;flex-direction:column;gap:2px"><span style="font-size:20px;font-weight:600;letter-spacing:-.01em">${t.who}</span><span style="font-size:13px;color:var(--text-muted)">${longDate(t.d)} · ${t.tm}</span></div><b style="font-size:36px;font-weight:600;letter-spacing:-.02em;font-variant-numeric:tabular-nums;color:${U().amtColor(t)}">${signed(t.amt)}</b></div>
${sec('Indeling', `<div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap">${catBtn(t, f.c, true)}${t.confirmed ? '' : '<span style="font-size:12px;font-weight:600;color:var(--botergoud)">Nog nakijken</span>'}</div>${f.b ? `<div style="display:flex;flex-direction:column;gap:6px;padding-top:6px"><div style="display:flex;justify-content:space-between;gap:8px;font-size:13px"><span>${f.b.kind === 'fixed' ? 'Vaste last' : 'Potje'} ${f.b.cat.name}</span><span style="color:var(--text-muted);font-variant-numeric:tabular-nums;white-space:nowrap">${budgetLine(f.b)}</span></div>${bar(f.b)}</div>` : ''}`)}
${f.refund || f.refundOf ? sec('Geld terug', refundRow(f)) : t.amt < 0 ? `<div style="display:flex">${quiet('link', 'Terugbetaling koppelen')}</div>` : ''}
${sec('Rekening', `<div style="display:flex;align-items:center;gap:12px">${U().logo(f.acc.bank, 36)}<span style="display:flex;flex-direction:column"><span style="font-size:14px;font-weight:500">${f.acc.name}</span><span style="font-size:12px;color:var(--text-muted)">${f.acc.detail}</span></span></div>`)}
${sec('Zoals de bank het schrijft', `<span class="tx-mono" style="font-size:12px;line-height:1.55;color:var(--text);word-break:break-word">${t.desc}</span>`)}
${past.length ? sec(`Eerder bij ${t.who}`, past.map(x => `<div style="display:flex;justify-content:space-between;gap:8px;min-height:32px;align-items:center;font-size:14px"><span style="color:var(--text-muted)">${shortDay(x.d)}</span><span style="font-variant-numeric:tabular-nums">${signed(x.amt)}</span></div>`).join(''), `<span style="font-size:12px;color:var(--text-muted)">${h.count} keer sinds mei</span>`) : ''}</div>`;
}

/* C · Tegenpartij: de transactie in de reeks van alle keren bij dezelfde partij. */
function C(t, o) {
  const f = facts(t), h = history(t.who), max = Math.max(...h.months.map(m => m.sum), 1), cur = at(t.d).getUTCMonth();
  const bars = h.months.map(m => `<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:6px;min-width:0"><span style="font-size:11px;font-weight:600;font-variant-numeric:tabular-nums;color:${m.m === cur ? 'var(--text)' : 'transparent'}">${eur(m.sum).replace(',00', '')}</span><span style="width:100%;max-width:44px;height:${Math.max(4, Math.round(m.sum / max * 88))}px;border-radius:8px;background:${m.m === cur ? 'var(--accent)' : 'var(--heat-1)'}"></span><span style="font-size:12px;color:${m.m === cur ? 'var(--text)' : 'var(--text-muted)'};font-weight:${m.m === cur ? 600 : 400}">${m.label}</span></div>`).join('');
  const list = h.all.slice(0, 8).map(x => { const me = x.id === t.id; return `<div style="display:flex;align-items:center;gap:10px;min-height:44px;${me ? 'margin:0 -10px;padding:0 10px;border-radius:12px;background:var(--accent-soft);' : ''}"><span style="flex:1;font-size:14px;${me ? 'font-weight:600' : ''}">${shortDay(x.d)}${me ? ' · deze' : ''}</span><span style="font-size:13px;color:var(--text-muted)">${store.acc(x.acc).name}</span><span style="width:96px;text-align:right;font-size:14px;font-variant-numeric:tabular-nums;${me ? 'font-weight:600' : ''}">${signed(x.amt)}</span></div>`; }).join('');
  const back = o.phone ? `<button data-act="close-detail" style="align-self:flex-start;display:flex;align-items:center;gap:2px;min-height:44px;padding:0 10px 0 4px;margin-left:-6px;border:0;background:none;font:inherit;font-size:15px;font-weight:500;color:var(--accent);cursor:pointer">${ico('left', 20, 2.4)}Transacties</button>` : '';
  return `<div style="display:flex;flex-direction:column;gap:20px;padding:${o.phone ? '12px 16px 40px' : '28px'}">${back}<div style="display:flex;align-items:center;gap:14px;padding-right:${o.phone ? 0 : 44}px">${U().chip(f.c, 52)}<span style="display:flex;flex-direction:column;gap:2px;min-width:0"><span style="font-size:22px;font-weight:600;letter-spacing:-.01em">${t.who}</span><span style="font-size:13px;color:var(--text-muted)">${h.count} keer sinds mei · gemiddeld ${eur(h.avg)}</span></span></div><div style="display:flex;align-items:flex-end;gap:8px;height:128px;padding:0 4px">${bars}</div><div style="display:flex;flex-direction:column;gap:12px;padding:16px;border-radius:18px;background:var(--surface-raised);border:1.5px solid var(--accent);box-shadow:var(--shadow-card)"><div style="display:flex;align-items:baseline;justify-content:space-between;gap:8px"><span style="font-size:14px;color:var(--text-muted)">${longDate(t.d)} · ${t.tm}</span><b style="font-size:22px;font-weight:600;font-variant-numeric:tabular-nums;color:${U().amtColor(t)}">${signed(t.amt)}</b></div><div style="display:flex;flex-wrap:wrap;align-items:center;gap:8px">${catBtn(t, f.c, true)}<span style="display:inline-flex;align-items:center;gap:6px;font-size:13px;color:var(--text-muted)">${U().logo(f.acc.bank, 20)}${f.acc.name}</span></div>${f.b ? `<div style="display:flex;flex-direction:column;gap:6px"><span style="font-size:13px;color:var(--text-muted)">${f.b.kind === 'fixed' ? 'Vaste last' : 'Potje'} ${f.b.cat.name}: ${budgetLine(f.b)}</span>${bar(f.b, 5)}</div>` : ''}${refundRow(f, true)}<span class="tx-mono" style="font-size:11px;line-height:1.5;color:var(--text-muted);word-break:break-word">${t.desc}</span></div><section style="display:flex;flex-direction:column;gap:6px"><div style="padding:0 2px">${lab(`Alle keren bij ${t.who}`)}</div><div style="display:flex;flex-direction:column;padding:4px 16px;border-radius:18px;background:var(--surface-sunken)">${list}</div></section><button data-act="cat" data-id="${t.id}" style="display:flex;align-items:center;gap:12px;min-height:56px;padding:6px 14px;border-radius:16px;border:1px solid var(--border);background:var(--surface-raised);font:inherit;text-align:left;cursor:pointer">${ico('repeat', 18, 2.2)}<span style="flex:1;display:flex;flex-direction:column"><span style="font-size:14px;font-weight:600">Alle keren bij ${t.who} indelen</span><span style="font-size:12px;color:var(--text-muted)">Kies een categorie, ook voor wat nog komt</span></span>${ico('right', 18, 2.2)}</button></div>`;
}

/* D · Bon: klein en zakelijk, zoals een kassabon; de banktekst is de hoofdzaak. */
function D(t, o) {
  const f = facts(t), line = (k, v) => `<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;min-height:30px"><span class="tx-mono" style="font-size:11px;letter-spacing:.06em;color:var(--text-subtle)">${k}</span><span style="min-width:0;font-size:13px;text-align:right;display:flex;align-items:center;gap:6px;justify-content:flex-end">${v}</span></div>`;
  const cut = '<div style="height:0;border-top:1.5px dashed var(--border);margin:2px -4px"></div>';
  return `<div style="display:flex;flex-direction:column;gap:10px;padding:${o.phone ? '14px 20px 28px' : '20px'}"><div style="display:flex;flex-direction:column;align-items:center;gap:4px;padding:${o.phone ? '8px 40px 4px' : '4px 0'};text-align:center">${U().chip(f.c, 40)}<span style="font-size:15px;font-weight:600;margin-top:4px">${t.who}</span><b style="font-size:30px;font-weight:600;letter-spacing:-.02em;font-variant-numeric:tabular-nums;color:${U().amtColor(t)}">${signed(t.amt)}</b></div>${cut}${line('DATUM', `<span class="tx-mono">${dmy(t.d)} ${t.tm}</span>`)}${line('REKENING', `${U().logo(f.acc.bank, 18)}${f.acc.name}`)}${line('CATEGORIE', catBtn(t, f.c))}${f.b ? line(f.b.kind === 'fixed' ? 'VASTE LAST' : 'POTJE', `<span style="color:var(--text-muted)">${budgetLine(f.b)}</span>`) : ''}${f.refund ? line('TERUG', `<span style="color:var(--success);font-weight:600;font-variant-numeric:tabular-nums">${signed(f.refund.amt)}</span><span style="color:var(--text-muted)">${f.refund.who}</span>`) : ''}${cut}<div class="tx-mono" style="font-size:12px;line-height:1.6;color:var(--text);word-break:break-word;padding:2px 0">${t.desc}</div>${cut}<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:4px">${quiet('repeat', 'Altijd zo', 'cat', t.id)}${t.amt < 0 && !f.refund ? quiet('link', 'Terug koppelen') : quiet('pencil', 'Categorie', 'cat', t.id)}</div></div>`;
}

/* Profiel · Rekeningen: volgorde door te slepen, oog om te verbergen in Transacties,
   en de rij klapt uit zoals live (delen, naam, ontkoppelen), nu als één blad met de rij. */
function Profiel(root) {
  root.style.position = 'relative'; root.style.overflow = 'hidden';
  root.innerHTML = `<div style="position:absolute;inset:0;overflow-y:auto;padding:16px 16px 40px;box-sizing:border-box;font-family:var(--font-sans);color:var(--text)"><div style="display:flex;flex-direction:column;gap:16px"><div style="display:flex;align-items:center;justify-content:space-between;padding-left:8px"><b style="font-size:30px;font-weight:600;letter-spacing:-.02em">Profiel</b><span style="width:48px;height:48px;display:grid;place-items:center"><span style="width:36px;height:36px;border-radius:999px;background:var(--member-yoran);color:#fff;display:grid;place-items:center;font-size:14px;font-weight:600">Y</span></span></div><div style="display:flex;flex-direction:column;gap:8px"><div style="padding:4px 4px 0;font-size:13px;font-weight:600;color:var(--text-muted)">Rekeningen</div><div style="display:flex;flex-direction:column;gap:2px;padding:6px;border-radius:var(--radius-lg);background:var(--surface-raised);border:1px solid var(--border);box-shadow:var(--shadow-card)"><div data-reklist style="display:flex;flex-direction:column;gap:2px"></div><div style="display:flex;align-items:center;justify-content:space-between;padding:0 4px 0 12px"><span style="display:flex;align-items:center;gap:8px;min-height:48px;font-size:14px;font-weight:600;color:var(--accent)">${ico('plus', 16, 2.4)}Rekening koppelen</span><span style="min-height:48px;display:flex;align-items:center;padding:0 12px;font-size:14px;font-weight:600;color:var(--text-muted)">Ophalen</span></div></div></div></div></div>`;
  const list = root.querySelector('[data-reklist]');
  const ui = { open:null, confirm:false, draft:null };
  const detailOf = a => store.hidden.has(a.id) ? 'Verborgen in Transacties' : a.shared ? 'Gedeeld met Imke · ' + a.detail.split(' · ').slice(1).join(' · ') : 'Privé' + (a.detail.includes('•') ? ' · ' + a.detail.split(' · ').slice(1).join(' · ') : '');
  const panel = a => {
    const remove = a.connected ? 'Ontkoppelen' : 'Weghalen', dirty = ui.draft != null && ui.draft.trim() && ui.draft !== a.name;
    const meta = a.connected ? a.consent : `Zonder koppeling · <span class="tx-mono" style="font-size:11px">${a.iban}</span>`;
    return `<div class="tx-in" style="display:flex;flex-direction:column;gap:12px;padding:2px 12px 12px 12px">
<button data-share="${a.id}" role="switch" aria-checked="${!!a.shared}" style="display:flex;align-items:center;gap:12px;min-height:56px;padding:8px 10px 8px 14px;border-radius:16px;border:0;background:var(--surface-raised);font:inherit;text-align:left;cursor:pointer;color:var(--text)"><span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px"><span style="font-size:15px;font-weight:500">Gedeeld met Imke</span><span style="font-size:12px;line-height:1.4;color:var(--text-muted);text-wrap:pretty">Imke kan deze rekening en de transacties inzien.</span></span>${X.ui.switchEl(!!a.shared)}</button>
<label style="display:flex;flex-direction:column;gap:6px"><span style="padding:0 4px;font-size:12px;font-weight:600;color:var(--text-muted)">Naam</span><span style="display:flex;align-items:center;gap:4px;height:48px;padding:0 4px 0 16px;border-radius:999px;background:var(--surface-raised);border:1px solid var(--border);box-sizing:border-box"><input data-name="${a.id}" value="${(ui.draft ?? a.name).replace(/"/g, '&quot;')}" maxlength="40" style="flex:1;min-width:0;border:0;outline:0;background:transparent;font:inherit;font-size:15px;color:var(--text)">${dirty ? `<button data-save="${a.id}" style="height:40px;padding:0 14px;border-radius:999px;border:0;background:var(--accent);color:var(--accent-fg);font:inherit;font-size:13px;font-weight:600;cursor:pointer">Opslaan</button>` : ''}</span></label>
<div style="display:flex;${ui.confirm ? 'flex-direction:column;align-items:stretch;gap:8px;padding:12px 14px;border-radius:16px;background:var(--surface-raised)' : 'align-items:center;justify-content:space-between;gap:12px;min-height:44px;padding:0 4px'}">${ui.confirm ? `<span style="font-size:13px;line-height:1.4;text-wrap:pretty">${a.connected ? 'Er komen geen nieuwe transacties meer bij. Wat er staat, blijft.' : 'De rekening gaat weg, en daarmee het herkennen van overboekingen ernaartoe.'}</span><span style="display:flex;justify-content:flex-end;gap:4px"><button data-cancel style="min-height:44px;padding:0 10px;border:0;background:none;font:inherit;font-size:14px;font-weight:600;color:var(--text-muted);cursor:pointer">Annuleren</button><button data-remove style="min-height:40px;padding:0 14px;border-radius:999px;border:0;background:var(--botergoud-soft);color:var(--botergoud);font:inherit;font-size:14px;font-weight:600;cursor:pointer">${remove}</button></span>` : `<span style="min-width:0;font-size:12px;color:var(--text-muted);font-variant-numeric:tabular-nums">${meta}</span><button data-ask style="flex:0 0 auto;min-height:44px;padding:0 4px;border:0;background:none;font:inherit;font-size:14px;font-weight:600;color:var(--text-muted);cursor:pointer">${remove}</button>`}</div></div>`;
  };
  const render = () => {
    list.innerHTML = store.accounts().map(a => { const off = store.hidden.has(a.id), open = ui.open === a.id; return `<div data-rek="${a.id}" style="position:relative;display:flex;flex-direction:column;border-radius:18px;background:${open ? 'var(--surface-sunken)' : 'var(--surface-raised)'};transition:background .2s,box-shadow .15s"><div data-toggle="${a.id}" aria-expanded="${open}" style="display:flex;align-items:center;gap:6px;min-height:64px;padding:0 6px 0 0;cursor:pointer"><span data-grip aria-label="Sleep om ${a.name} te verplaatsen" style="flex:0 0 auto;width:26px;height:52px;display:grid;place-items:center;color:var(--text-subtle);cursor:grab;touch-action:none">${ico('grip', 16, 2)}</span>${X.ui.logo(a.bank, 40, off)}<span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;margin-left:2px"><span style="font-size:15px;font-weight:500;letter-spacing:-.005em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;${off ? 'color:var(--text-muted)' : ''}">${a.name}</span><span style="font-size:13px;color:var(--text-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-variant-numeric:tabular-nums">${detailOf(a)}</span></span><button data-eye="${a.id}" aria-pressed="${off}" aria-label="${off ? 'Tonen' : 'Verbergen'} in Transacties" title="${off ? 'Tonen' : 'Verbergen'} in Transacties" style="flex:0 0 auto;width:40px;height:40px;margin:-4px;box-sizing:content-box;border:4px solid transparent;background-clip:padding-box;border-radius:999px;display:grid;place-items:center;cursor:pointer;background-color:${off ? 'var(--surface-sunken)' : 'transparent'};color:${off ? 'var(--text)' : 'var(--text-subtle)'}">${ico(off ? 'eyeoff' : 'eye', 18, 2)}</button><span style="flex:0 0 auto;width:22px;display:grid;place-items:center;color:var(--text-subtle);transition:transform .2s;${open ? 'transform:rotate(180deg)' : ''}">${ico('down', 18, 2.2)}</span></div>${open ? panel(a) : ''}</div>`; }).join('');
  };
  list.addEventListener('click', e => {
    const t = e.target, acc = id => store.acc(id);
    const eye = t.closest('[data-eye]');
    if (eye) { const id = eye.dataset.eye; if (store.hidden.has(id)) store.hidden.delete(id); else if (store.visible().length > 1) store.hidden.add(id); render(); store.emit(); return; }
    const sh = t.closest('[data-share]'); if (sh) { const a = acc(sh.dataset.share); a.shared = !a.shared; render(); return; }
    const sv = t.closest('[data-save]'); if (sv) { acc(sv.dataset.save).name = ui.draft.trim(); ui.draft = null; render(); store.emit(); return; }
    if (t.closest('[data-ask]')) { ui.confirm = true; render(); return; }
    if (t.closest('[data-cancel]')) { ui.confirm = false; render(); return; }
    if (t.closest('[data-remove]')) { ui.confirm = false; render(); return; }
    if (t.closest('[data-grip]') || t.closest('input,label')) return;
    const tg = t.closest('[data-toggle]'); if (tg) { ui.open = ui.open === tg.dataset.toggle ? null : tg.dataset.toggle; ui.confirm = false; ui.draft = null; render(); }
  });
  list.addEventListener('input', e => {
    if (!e.target.matches('[data-name]')) return;
    const a = store.acc(e.target.dataset.name), had = ui.draft != null && ui.draft.trim() && ui.draft !== a.name;
    ui.draft = e.target.value;
    const now = ui.draft.trim() && ui.draft !== a.name;
    if (!!had !== !!now) { const pos = e.target.selectionStart; render(); const inp = list.querySelector('[data-name]'); inp.focus(); inp.setSelectionRange(pos, pos); }
  });
  let drag = null;
  list.addEventListener('pointerdown', e => {
    const g = e.target.closest('[data-grip]'); if (!g) return;
    if (ui.open) { ui.open = null; render(); }
    const id = g.closest('[data-rek]').dataset.rek, row = list.querySelector(`[data-rek="${id}"]`), grip = row.querySelector('[data-grip]');
    const f = root.getBoundingClientRect(), k = f.width / root.offsetWidth || 1;
    drag = { row, y: e.clientY, k }; grip.setPointerCapture(e.pointerId);
    Object.assign(row.style, { zIndex:2, boxShadow:'var(--shadow-raised)', transition:'none' }); grip.style.cursor = 'grabbing';
  });
  list.addEventListener('pointermove', e => {
    if (!drag) return;
    const { row, k } = drag; let dy = (e.clientY - drag.y) / k;
    const next = row.nextElementSibling, prev = row.previousElementSibling;
    if (next && dy > next.offsetHeight / 2) { list.insertBefore(next, row); drag.y += (next.offsetHeight + 2) * k; dy -= next.offsetHeight + 2; }
    else if (prev && dy < -prev.offsetHeight / 2) { list.insertBefore(row, prev); drag.y -= (prev.offsetHeight + 2) * k; dy += prev.offsetHeight + 2; }
    row.style.transform = `translateY(${dy}px)`;
  });
  const end = () => {
    if (!drag) return;
    Object.assign(drag.row.style, { transform:'', zIndex:'', boxShadow:'', transition:'' });
    drag = null;
    store.order = [...list.querySelectorAll('[data-rek]')].map(r => r.dataset.rek);
    render(); store.emit();
  };
  list.addEventListener('pointerup', end); list.addEventListener('pointercancel', end);
  render();
  store.subs.push(() => { if (!drag && !list.contains(document.activeElement)) render(); });
}

window.TX2D = { content: (v, t, o) => ({ A, B, C, D })[v](t, o), Profiel };
})();
